{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sad.jetpack.architecture.componentization",
    "module": "plugin",
    "version": "1.0.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fbv2exkrc5ahpgfrtje2pe2kea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 11359,
          "sha512": "79806361923037631741fd2318ba7c5c72af16871c47316c5d00427ad041ed3a7fbd276703a42e701a50f5e8e4af2924b12425ac3df6e7e702c6b88a82bf92e1",
          "sha256": "d65dded1d0e53f5cd7524b42f292f3c3d05e8de5ca17ef6da39b5b64f4e9a312",
          "sha1": "76daa2e8b3ed2ae5060dd5a2cbcad680a1acc818",
          "md5": "125c580a37a6f64a3fce2fa4fda1cb29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 11359,
          "sha512": "79806361923037631741fd2318ba7c5c72af16871c47316c5d00427ad041ed3a7fbd276703a42e701a50f5e8e4af2924b12425ac3df6e7e702c6b88a82bf92e1",
          "sha256": "d65dded1d0e53f5cd7524b42f292f3c3d05e8de5ca17ef6da39b5b64f4e9a312",
          "sha1": "76daa2e8b3ed2ae5060dd5a2cbcad680a1acc818",
          "md5": "125c580a37a6f64a3fce2fa4fda1cb29"
        }
      ]
    }
  ]
}
