{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sad.jetpack.architecture.componentization",
    "module": "plugin",
    "version": "1.0.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lvbxro5dtvfrnnuomxsiymd66e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 11359,
          "sha512": "0431c912f68bc5708b0f6347b0d75b81f8d13f46993351a4e02b7571ec746acb9d3e0f107eef06a009e79a878adbfcd654e67649ff362b6ef241cfbd6c1d67eb",
          "sha256": "a85a16583892d5b329a16da1ee5f00e6b2938223919aaef61e8bbb525cf50dba",
          "sha1": "70b44e61e0a803774da394834edb1938798f328e",
          "md5": "9172ed90acebff4c068db6847a77595c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sad.jetpack.architecture.componentization",
          "module": "annotation",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.sad.jetpack.lib.classscanner",
          "module": "ClassScanner",
          "version": {
            "requires": "1.0.1-Beta6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 11359,
          "sha512": "0431c912f68bc5708b0f6347b0d75b81f8d13f46993351a4e02b7571ec746acb9d3e0f107eef06a009e79a878adbfcd654e67649ff362b6ef241cfbd6c1d67eb",
          "sha256": "a85a16583892d5b329a16da1ee5f00e6b2938223919aaef61e8bbb525cf50dba",
          "sha1": "70b44e61e0a803774da394834edb1938798f328e",
          "md5": "9172ed90acebff4c068db6847a77595c"
        }
      ]
    }
  ]
}
