{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sad.jetpack.architecture.appgo",
    "module": "plugin",
    "version": "1.0.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ndt75mdxqreifa75mob4igz4di"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 32595,
          "sha512": "d44499b0fe9524de510d6c6a6b936c6b936925d04caaac1add2ba30ca8842c35efe83ff34de8ffda238464b591e5d20d770fea3e0025a053cf93dc787f0fd30c",
          "sha256": "6004104b75c2b40de27ff0dd27a50b8dcab734868cc17cb1fe0721e31f23223c",
          "sha1": "a5e674a12ca243133f048541c28daa6180db3349",
          "md5": "663369636354c5e1031640282c8dfce9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sad.jetpack.architecture.appgo",
          "module": "annotation",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.sad.jetpack.lib.classscanner",
          "module": "ClassScanner",
          "version": {
            "requires": "1.0.1-Beta5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 32595,
          "sha512": "d44499b0fe9524de510d6c6a6b936c6b936925d04caaac1add2ba30ca8842c35efe83ff34de8ffda238464b591e5d20d770fea3e0025a053cf93dc787f0fd30c",
          "sha256": "6004104b75c2b40de27ff0dd27a50b8dcab734868cc17cb1fe0721e31f23223c",
          "sha1": "a5e674a12ca243133f048541c28daa6180db3349",
          "md5": "663369636354c5e1031640282c8dfce9"
        }
      ]
    }
  ]
}
