{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sad.jetpack.architecture.appgo",
    "module": "plugin",
    "version": "1.0.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jicyg53fozhkharjeakauiu3o4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 32947,
          "sha512": "c77a93ba2a10357a758511425562e9eb15ce18ef049eb3903e56c0bdc9ab4ccabb807171c4fe88fb07b21fd47281863c526e177111dafad3c8dbf04a99fe8041",
          "sha256": "5e73a12a93e905522f43a78ccb70cd85e11c7e4e8a55d15ee8603f2071e9ea4d",
          "sha1": "cbe341dfde5bd8cf3626daf8f0dcf595bfc24be6",
          "md5": "fb3a40c2a1ab97e286af1d391916e28e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sad.jetpack.architecture.appgo",
          "module": "annotation",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.sad.jetpack.lib.classscanner",
          "module": "ClassScanner",
          "version": {
            "requires": "1.0.1-Beta6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 32947,
          "sha512": "c77a93ba2a10357a758511425562e9eb15ce18ef049eb3903e56c0bdc9ab4ccabb807171c4fe88fb07b21fd47281863c526e177111dafad3c8dbf04a99fe8041",
          "sha256": "5e73a12a93e905522f43a78ccb70cd85e11c7e4e8a55d15ee8603f2071e9ea4d",
          "sha1": "cbe341dfde5bd8cf3626daf8f0dcf595bfc24be6",
          "md5": "fb3a40c2a1ab97e286af1d391916e28e"
        }
      ]
    }
  ]
}
