{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sad.jetpack.architecture.appgo",
    "module": "plugin",
    "version": "1.0.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "paetdemswzgydkoyt5goj33q5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 31520,
          "sha512": "1bfefe5c6b7e59cf56aaf6673daf7e280462d156dccfa7136840ddca2e6d1184e282f22c87f4bc8e6e9ff425f6a7c2ed54b37b5881f04ff8e5d7aebba48e47e4",
          "sha256": "5abf6a4af6116b5af2da25def9adc4dc61cc0da4ecacc51d18db45930e90e064",
          "sha1": "f3df965cc3095c2cea2205963869dec6cb6b23c2",
          "md5": "ac9a5bef5a2ae764091f13491f5fb2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sad.jetpack.architecture.appgo",
          "module": "annotation",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.sad.jetpack.lib.classscanner",
          "module": "ClassScanner",
          "version": {
            "requires": "1.0.1-Beta6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-test.jar",
          "url": "plugin-1.0.0-test.jar",
          "size": 31520,
          "sha512": "1bfefe5c6b7e59cf56aaf6673daf7e280462d156dccfa7136840ddca2e6d1184e282f22c87f4bc8e6e9ff425f6a7c2ed54b37b5881f04ff8e5d7aebba48e47e4",
          "sha256": "5abf6a4af6116b5af2da25def9adc4dc61cc0da4ecacc51d18db45930e90e064",
          "sha1": "f3df965cc3095c2cea2205963869dec6cb6b23c2",
          "md5": "ac9a5bef5a2ae764091f13491f5fb2bf"
        }
      ]
    }
  ]
}
